[project]
name = "ai-tasks-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "grpcio>=1.76.0",
    "grpcio-tools>=1.76.0",
    "jinja2>=3.1.6",
    "pytest>=9.0.2",
]
